/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MarcaController;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Marca;

/**
 *
 * @author pedrohenrique
 */
public class TelaCadMarca extends javax.swing.JInternalFrame {

    MarcaController controller; //Objeto responsável pelo ControllerCidade
    JDesktopPane areaTrabalho;
    TelaPrincipal telaPrincipal;
    DefaultTableModel tbMarcas;
    ArrayList<Marca> marcas;
    Marca m; 
    
    public TelaCadMarca() {
        initComponents();
        controller = new MarcaController();
        tbMarcas = (DefaultTableModel) jTMarcas.getModel();
        this.listarMarcas(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBnovo = new javax.swing.JButton();
        JBalterar = new javax.swing.JButton();
        JBexcluir = new javax.swing.JButton();
        JBcancelar = new javax.swing.JButton();
        JBsair = new javax.swing.JButton();
        JBsalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTFpesquisar = new javax.swing.JTextField();
        JBpesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        JTFcodigo = new javax.swing.JTextField();
        JTFmarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMarcas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Marcas");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        JBnovo.setText("Nova");
        JBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnovoActionPerformed(evt);
            }
        });

        JBalterar.setText("Alterar");
        JBalterar.setEnabled(false);
        JBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBalterarActionPerformed(evt);
            }
        });

        JBexcluir.setText("Excluir");
        JBexcluir.setEnabled(false);
        JBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexcluirActionPerformed(evt);
            }
        });

        JBcancelar.setText("Cancelar");
        JBcancelar.setEnabled(false);
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });

        JBsair.setText("Sair");
        JBsair.setEnabled(false);
        JBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsairActionPerformed(evt);
            }
        });

        JBsalvar.setText("Salvar");
        JBsalvar.setToolTipText("");
        JBsalvar.setEnabled(false);
        JBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JBexcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBalterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBsalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBnovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBalterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBexcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBcancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBsair)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel1.setText("Pesquisar:");

        JTFpesquisar.setText("Digite o código ou nome da marca");
        JTFpesquisar.setToolTipText("");
        JTFpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFpesquisarMouseClicked(evt);
            }
        });
        JTFpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFpesquisarActionPerformed(evt);
            }
        });
        JTFpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFpesquisarKeyPressed(evt);
            }
        });

        JBpesquisar.setText("Pesquisar");
        JBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        JTFcodigo.setEnabled(false);
        JTFcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcodigoActionPerformed(evt);
            }
        });

        JTFmarca.setEnabled(false);
        JTFmarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFmarcaFocusGained(evt);
            }
        });
        JTFmarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFmarcaMouseClicked(evt);
            }
        });
        JTFmarca.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JTFmarcaPropertyChange(evt);
            }
        });

        jLabel3.setText("Marca:");

        jTMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Marca"
            }
        ));
        jTMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMarcasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTMarcas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBpesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFmarca)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 350, Short.MAX_VALUE))))
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBpesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTFmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnovoActionPerformed
        this.habilitarCampos(2);
    }//GEN-LAST:event_JBnovoActionPerformed

    private void JBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBalterarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente atualizar os dados da marca", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        if (opcao == 0) {
            controller.alterar(this.criarObjeto());
            this.limparCampos();
            this.habilitarCampos(3);
            this.listarMarcas(1);
        }
    }//GEN-LAST:event_JBalterarActionPerformed

    private void JBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexcluirActionPerformed
int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a marca", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);

        if (opcao == 0) {
            controller.deletar(this.criarObjeto());
            this.limparCampos();
            this.habilitarCampos(3);
            this.listarMarcas(1);
        }
    }//GEN-LAST:event_JBexcluirActionPerformed

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(3);
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void JBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsairActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBsairActionPerformed

    private void JTFpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFpesquisarMouseClicked
        JTFpesquisar.setText("");
    }//GEN-LAST:event_JTFpesquisarMouseClicked

    private void JTFpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFpesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.pesquisar();
        }
    }//GEN-LAST:event_JTFpesquisarKeyPressed

    private void JBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpesquisarActionPerformed
        this.pesquisar();
    }//GEN-LAST:event_JBpesquisarActionPerformed

    private void JTFpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFpesquisarActionPerformed

    private void JTFcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcodigoActionPerformed

    private void JTFmarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFmarcaFocusGained
        JTFmarca.setBackground(Color.white);
    }//GEN-LAST:event_JTFmarcaFocusGained

    private void JTFmarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFmarcaMouseClicked
        if (JTFmarca.getText().equals("O campo marca não pode ficar vazio")) {
            JTFmarca.setText("");
            JTFmarca.setBackground(Color.white);
        }
    }//GEN-LAST:event_JTFmarcaMouseClicked

    private void JTFmarcaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JTFmarcaPropertyChange
        JTFmarca.setBackground(Color.white);
    }//GEN-LAST:event_JTFmarcaPropertyChange

    private void jTMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMarcasMouseClicked
        this.habilitarCampos(1);
        pesquisar();
    }//GEN-LAST:event_jTMarcasMouseClicked

    private void JBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalvarActionPerformed
        if (this.verificarCampos()) {
            controller.cadastrar(this.criarObjeto());
            this.limparCampos();
            this.habilitarCampos(3);
            this.listarMarcas(1);
        }
    }//GEN-LAST:event_JBsalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBalterar;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBexcluir;
    private javax.swing.JButton JBnovo;
    private javax.swing.JButton JBpesquisar;
    private javax.swing.JButton JBsair;
    private javax.swing.JButton JBsalvar;
    private javax.swing.JTextField JTFcodigo;
    private javax.swing.JTextField JTFmarca;
    private javax.swing.JTextField JTFpesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTMarcas;
    // End of variables declaration//GEN-END:variables
    
    public void limparCampos() {
        JTFcodigo.setText("");
        JTFmarca.setText("");
        JTFpesquisar.setText("Digite o código ou nome da cidade");
    }

    public void habilitarCampos(int btn) {
        switch (btn) {
            case 1://Botão Pesquisar
                JBnovo.setEnabled(false);
                JBalterar.setEnabled(true);
                JBexcluir.setEnabled(true);
                JBcancelar.setEnabled(true);
                JBsair.setEnabled(false);
                JBsalvar.setEnabled(false);
                JTFmarca.setEnabled(true);
                break;
            case 2://Botão Novo
                JBsalvar.setEnabled(true);
                JBcancelar.setEnabled(true);
                JBpesquisar.setEnabled(false);
                JBalterar.setEnabled(false);
                JBnovo.setEnabled(false);
                JBsair.setEnabled(false);
                JBexcluir.setEnabled(false);
                JTFpesquisar.setEnabled(false);
                JTFmarca.setEnabled(true);
                break;
            case 3://Botões Salvar, Alterar, Excluir e Cancelar
                JBpesquisar.setEnabled(true);
                JTFpesquisar.setEnabled(true);
                JTFmarca.setEnabled(false);
                JBnovo.setEnabled(true);
                JBsair.setEnabled(true);
                JBsalvar.setEnabled(false);
                JBalterar.setEnabled(false);
                JBexcluir.setEnabled(false);
                JBcancelar.setEnabled(false);
                break;
            default:
                break;
        }
    }

    public Marca criarObjeto() {
        Marca m = new Marca();

        m.setNome(JTFmarca.getText());
        if (JTFcodigo.getText().equals("")) {
            m.setCodigo(0);
        } else {
            m.setCodigo(Integer.parseInt(JTFcodigo.getText()));
        }

        return m;
    }

    public void pesquisar() {
        
        m = controller.pesquisar(JTFpesquisar.getText());
        
        if (m.getCodigo() == 0) {
            this.limparCampos();
            this.habilitarCampos(3);
            JOptionPane.showMessageDialog(null, "Marca não encontrada", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
            this.listarMarcas(2);
        } else {
            JTFcodigo.setText(Integer.toString(m.getCodigo()));
            JTFmarca.setText(m.getNome());
            habilitarCampos(1);
        }
    }
    
    public boolean verificarCampos() {

        boolean preenchido = true;

        if (JTFmarca.getText().isEmpty()) {
            JTFmarca.setText("O campo marca não pode ficar vazio");
            JTFmarca.setBackground(Color.YELLOW);
            preenchido = false;
        }
        
        return preenchido;
    }
    
    public void listarMarcas(int opcao) {

        if(opcao == 1){
            marcas = controller.selecionarMarcas();
        } else{
            marcas = controller.selecionarMarcas(JTFpesquisar.getText());
        }
        
        removerLinhas();
        
        for (Marca m : marcas) {
            tbMarcas.addRow(new Object[]{m.getCodigo(), m.getNome()});
        }
    }

    public void removerLinhas() {
        int linhas = tbMarcas.getRowCount();
        for (int i = linhas - 1; i >= 0; i--) {
            tbMarcas.removeRow(i);
        }

    }
    
}
