/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CidadeController;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.DesktopPaneUI;
import javax.swing.table.DefaultTableModel;
import model.Cidade;

/**
 *
 * @author Pedro
 */
public class TelaTabelaCidadeInternalFrame extends javax.swing.JInternalFrame {

    CidadeController controller;
    Cidade cid;
    DefaultTableModel tbCidades;
    TelaCadCidadeInternalFrame cadCid;
    ArrayList<Cidade> cidades;
    
    JDesktopPane areaTrabalho; 
    TelaPrincipal telaPrincipal;
    
    public TelaTabelaCidadeInternalFrame() {
        initComponents();
        controller = new CidadeController();
        tbCidades = (DefaultTableModel) jTCidades.getModel();
        this.listarCidades();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFpesquisar = new javax.swing.JTextField();
        JBpesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCidades = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        JBnovo = new javax.swing.JButton();
        JBalterar = new javax.swing.JButton();
        JBexcluir = new javax.swing.JButton();
        JBcancelar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Cidades");

        jLabel1.setText("Pesquisar:");

        JTFpesquisar.setText("Digite o código, nome ou UF da cidade");
        JTFpesquisar.setToolTipText("");
        JTFpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFpesquisarMouseClicked(evt);
            }
        });
        JTFpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFpesquisarKeyPressed(evt);
            }
        });

        JBpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        JBpesquisar.setText("Pesquisar");
        JBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpesquisarActionPerformed(evt);
            }
        });

        jTCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cidade", "UF", "País"
            }
        ));
        jTCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCidades);

        JBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        JBnovo.setText("Nova");
        JBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnovoActionPerformed(evt);
            }
        });

        JBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        JBalterar.setText("Alterar");
        JBalterar.setEnabled(false);
        JBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBalterarActionPerformed(evt);
            }
        });

        JBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        JBexcluir.setText("Excluir");
        JBexcluir.setEnabled(false);
        JBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexcluirActionPerformed(evt);
            }
        });

        JBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        JBcancelar.setText("Cancelar");
        JBcancelar.setEnabled(false);
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(JBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(JBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(JBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnovo)
                    .addComponent(JBalterar)
                    .addComponent(JBexcluir)
                    .addComponent(JBcancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFpesquisarMouseClicked
        JTFpesquisar.setText("");
    }//GEN-LAST:event_JTFpesquisarMouseClicked

    private void JTFpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFpesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pesquisar();
        }
    }//GEN-LAST:event_JTFpesquisarKeyPressed

    private void JBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_JBpesquisarActionPerformed

    private void jTCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCidadesMouseClicked
        habilitarCampos(1);
    }//GEN-LAST:event_jTCidadesMouseClicked

    private void JBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnovoActionPerformed
        cadCid = new TelaCadCidadeInternalFrame();
        cadCid.setVisible(true);
        cadCid.moveToFront();
        cadCid.setOpcao(1);
        cadCid.setAreaTrabalho(this.getAreaTrabalho());
        getTelaPrincipal().centralizarForm(cadCid);
        getAreaTrabalho().add(cadCid);
        this.dispose();

    }//GEN-LAST:event_JBnovoActionPerformed

    private void JBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBalterarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar os dados da cidade", 
                    "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        if (opcao == 0) {
            controller.alterar(this.criarObjeto());
            this.limparCampos();
            this.habilitarCampos(3);
        }
    }//GEN-LAST:event_JBalterarActionPerformed

    private void JBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexcluirActionPerformed

        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a cidade", 
                "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);

        if (opcao == 0) {
            controller.deletar(this.criarObjeto());
            limparCampos();
            habilitarCampos(3);
            tbCidades.removeRow(jTCidades.getSelectedRow());
        }
    }//GEN-LAST:event_JBexcluirActionPerformed

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        this.limparCampos();
        habilitarCampos(3);

    }//GEN-LAST:event_JBcancelarActionPerformed

    public void limparCampos() {
        JTFpesquisar.setText("Digite o código ou nome da cidade");
    }

    public void habilitarCampos(int btn) {
        switch (btn) {
            case 1://Botão Pesquisar
                JBnovo.setEnabled(false);
                JBalterar.setEnabled(true);
                JBexcluir.setEnabled(true);
                JBcancelar.setEnabled(true);
                break;
            case 2://Botão Novo
                TelaCadCidadeJFrame cadCidade = new TelaCadCidadeJFrame();
                cadCidade.setVisible(true);
                break;
            case 3://Botões Salvar, Alterar, Excluir e Cancelar
                JBpesquisar.setEnabled(true);
                JTFpesquisar.setEnabled(true);
                JBnovo.setEnabled(true);
                JBalterar.setEnabled(false);
                JBexcluir.setEnabled(false);
                JBcancelar.setEnabled(false);
                break;
            default:
                break;
        }
    }

    public Cidade criarObjeto() {
        cid = new Cidade();

        cid.setNome(String.valueOf(jTCidades.getValueAt(jTCidades.getSelectedRow(), 1)));
        cid.setUf(String.valueOf(jTCidades.getValueAt(jTCidades.getSelectedRow(), 2)));
        cid.setPais(String.valueOf(jTCidades.getValueAt(jTCidades.getSelectedRow(), 3)));
        cid.setCodigo(Integer.parseInt(jTCidades.getValueAt(jTCidades.getSelectedRow(), 0).toString()));

        return cid;
    }

    public void pesquisar() {
        cidades = controller.pesquisarCidades(JTFpesquisar.getText());

        if (cidades.isEmpty()) {
            this.limparCampos();
            this.habilitarCampos(3);
            JOptionPane.showMessageDialog(null, "Cidade não encontrada", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            removerLinhas();

            for (Cidade cid : cidades) {
                tbCidades.addRow(new Object[]{cid.getCodigo(), cid.getNome(), cid.getUf(), cid.getPais()});
            }

            habilitarCampos(1);
        }
    }

    public void listarCidades() {

        cidades = controller.selecionarCidades();
        
        removerLinhas();
        
        for (Cidade cid : cidades) {
            tbCidades.addRow(new Object[]{cid.getCodigo(), cid.getNome(), cid.getUf(), cid.getPais()});
        }
    }

    public void removerLinhas() {
        int linhas = tbCidades.getRowCount();
        for (int i = linhas - 1; i >= 0; i--) {
            tbCidades.removeRow(i);
        }

    }

    public void setAreaTrabalho(JDesktopPane areaTrabalho) {
        this.areaTrabalho = areaTrabalho;
    }

    public JDesktopPane getAreaTrabalho() {
        return this.areaTrabalho;
    }
    
    public void setTelaPrincipal(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }

    public TelaPrincipal getTelaPrincipal() {
        return this.telaPrincipal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBalterar;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBexcluir;
    private javax.swing.JButton JBnovo;
    private javax.swing.JButton JBpesquisar;
    private javax.swing.JTextField JTFpesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTCidades;
    // End of variables declaration//GEN-END:variables
}
