/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CidadeController;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import model.Cidade;

/**
 *
 * @author Pedro
 */
public class TelaTabelaCidadeJFrame extends javax.swing.JFrame {

    CidadeController controller;
    Cidade cid;
    DefaultTableModel tbCidades;
    TelaCadCidadeJFrame cadCid;
    
    public TelaTabelaCidadeJFrame() {
        initComponents();
        controller = new CidadeController();
        tbCidades = (DefaultTableModel) jTCidades.getModel();
        listarCidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFpesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JBpesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCidades = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        JBnovo = new javax.swing.JButton();
        JBalterar = new javax.swing.JButton();
        JBexcluir = new javax.swing.JButton();
        JBcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cidades");

        JTFpesquisar.setText("Digite o código ou nome da cidade");
        JTFpesquisar.setToolTipText("");
        JTFpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFpesquisarMouseClicked(evt);
            }
        });
        JTFpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFpesquisarKeyPressed(evt);
            }
        });

        jLabel1.setText("Pesquisar:");

        JBpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        JBpesquisar.setText("Pesquisar");
        JBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpesquisarActionPerformed(evt);
            }
        });

        jTCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cidade", "UF", "País"
            }
        ));
        jTCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCidades);

        JBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        JBnovo.setText("Nova");
        JBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnovoActionPerformed(evt);
            }
        });

        JBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        JBalterar.setText("Alterar");
        JBalterar.setEnabled(false);
        JBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBalterarActionPerformed(evt);
            }
        });

        JBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        JBexcluir.setText("Excluir");
        JBexcluir.setEnabled(false);
        JBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexcluirActionPerformed(evt);
            }
        });

        JBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        JBcancelar.setText("Cancelar");
        JBcancelar.setEnabled(false);
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(JBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(JBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(JBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnovo)
                    .addComponent(JBalterar)
                    .addComponent(JBexcluir)
                    .addComponent(JBcancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFpesquisarMouseClicked
        JTFpesquisar.setText("");
    }//GEN-LAST:event_JTFpesquisarMouseClicked

    private void JTFpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFpesquisarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            pesquisar();
        }
    }//GEN-LAST:event_JTFpesquisarKeyPressed

    private void JBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_JBpesquisarActionPerformed

    private void JBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnovoActionPerformed
        TelaCadCidadeJFrame cadCid = new TelaCadCidadeJFrame();
        cadCid.setVisible(true);
    }//GEN-LAST:event_JBnovoActionPerformed

    private void JBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBalterarActionPerformed
        cadCid = new TelaCadCidadeJFrame();
        cadCid.setVisible(true);
        cadCid.pesquisar(Integer.parseInt(jTCidades.getValueAt(jTCidades.getSelectedRow(), 0).toString()));
       
    }//GEN-LAST:event_JBalterarActionPerformed

    private void JBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexcluirActionPerformed

        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a cidade", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);

        if (opcao == 0) {
            controller.deletar(this.criarObjeto());
            limparCampus();
            habilitarCampus(3);
            tbCidades.removeRow(jTCidades.getSelectedRow());
        }

    }//GEN-LAST:event_JBexcluirActionPerformed

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        this.limparCampus();
        habilitarCampus(3);
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void jTCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCidadesMouseClicked
        habilitarCampus(1);
    }//GEN-LAST:event_jTCidadesMouseClicked

    public void limparCampus() {
        JTFpesquisar.setText("Digite o código ou nome da cidade");
    }

    public void habilitarCampus(int btn) {
        switch (btn) {
            case 1://Botão Pesquisar
                JBnovo.setEnabled(false);
                JBalterar.setEnabled(true);
                JBexcluir.setEnabled(true);
                JBcancelar.setEnabled(true);
                break;
            case 2://Botão Novo
                TelaCadCidadeJFrame cadCidade = new TelaCadCidadeJFrame();
                cadCidade.setVisible(true);
                break;
            case 3://Botões Salvar, Alterar, Excluir e Cancelar
                JBpesquisar.setEnabled(true);
                JTFpesquisar.setEnabled(true);
                JBnovo.setEnabled(true);
                JBalterar.setEnabled(false);
                JBexcluir.setEnabled(false);
                JBcancelar.setEnabled(false);
                break;
            default:
                break;
        }
    }

    public Cidade criarObjeto(){
        cid = new Cidade();
        
        cid.setNome(String.valueOf(jTCidades.getValueAt(jTCidades.getSelectedRow(), 1)));
        cid.setUf(String.valueOf(jTCidades.getValueAt(jTCidades.getSelectedRow(), 2)));
        cid.setPais(String.valueOf(jTCidades.getValueAt(jTCidades.getSelectedRow(), 3)));
        cid.setCodigo(Integer.parseInt(jTCidades.getValueAt(jTCidades.getSelectedRow(), 0).toString()));
        
        return cid;
    }
    
    public void pesquisar(){
        cid = controller.pesquisar(JTFpesquisar.getText());
        
        if (cid.getCodigo() == 0) {
            this.limparCampus();
            this.habilitarCampus(3);
            JOptionPane.showMessageDialog(null, "Cidade não encontrada", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            tbCidades.addRow(new Object[]{cid.getCodigo(), cid.getNome(), cid.getUf(), cid.getPais()});
           
            habilitarCampus(1);
        }
    }
    
    public void listarCidades(){
        
        ArrayList<Cidade> cidades = controller.selecionarCidades();
        
        for (Cidade cid : cidades) {
            tbCidades.addRow(new Object[]{cid.getCodigo(), cid.getNome(), cid.getUf(), cid.getPais()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaCidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaCidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaCidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaCidadeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabelaCidadeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBalterar;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBexcluir;
    private javax.swing.JButton JBnovo;
    private javax.swing.JButton JBpesquisar;
    private javax.swing.JTextField JTFpesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTCidades;
    // End of variables declaration//GEN-END:variables
}
