/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.UsuarioDAO;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author PC18
 */
public class TelaCadUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public TelaCadUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFpesquisa = new javax.swing.JTextField();
        JBpesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JTFcodigo = new javax.swing.JTextField();
        JTFnome = new javax.swing.JTextField();
        JTFemail = new javax.swing.JTextField();
        JTFsenha = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        JBnovo = new javax.swing.JButton();
        JBsalvar = new javax.swing.JButton();
        JBalterar = new javax.swing.JButton();
        JBexcluir = new javax.swing.JButton();
        JBcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pesquisar:");

        JBpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        JBpesquisar.setText("Pesquisar");
        JBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Email:");

        jLabel5.setText("Senha:");

        JTFcodigo.setEnabled(false);

        JTFnome.setEnabled(false);

        JTFemail.setEnabled(false);
        JTFemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFemailActionPerformed(evt);
            }
        });

        JTFsenha.setEnabled(false);

        JBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        JBnovo.setText("Novo");
        JBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnovoActionPerformed(evt);
            }
        });

        JBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/gravar.png"))); // NOI18N
        JBsalvar.setText("Salvar");
        JBsalvar.setEnabled(false);
        JBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalvarActionPerformed(evt);
            }
        });

        JBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        JBalterar.setText("Alterar");
        JBalterar.setEnabled(false);
        JBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBalterarActionPerformed(evt);
            }
        });

        JBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        JBexcluir.setText("Excluir");
        JBexcluir.setEnabled(false);
        JBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexcluirActionPerformed(evt);
            }
        });

        JBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        JBcancelar.setText("Cancelar");
        JBcancelar.setEnabled(false);
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFpesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBpesquisar)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JTFnome)
                            .addComponent(JTFemail)
                            .addComponent(JTFsenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBnovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBalterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBcancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBsalvar)
                        .addComponent(JBalterar)
                        .addComponent(JBexcluir)
                        .addComponent(JBcancelar))
                    .addComponent(JBnovo))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFemailActionPerformed

    private void JBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnovoActionPerformed
        JBsalvar.setEnabled(true);
        JBcancelar.setEnabled(true);
        JBpesquisar.setEnabled(false);
        JTFpesquisa.setEnabled(false);
        JBnovo.setEnabled(false);
        JTFnome.setEnabled(true);
        JTFemail.setEnabled(true);
        JTFsenha.setEnabled(true);
    }//GEN-LAST:event_JBnovoActionPerformed

    private void JBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalvarActionPerformed
        String nome = JTFnome.getText();
        String pais = JTFemail.getText();
        String uf = (String) JTFsenha.getText();
        
        Usuario usuario = new Usuario();
        usuario.setNome(nome);
        usuario.setEmail(pais);
        usuario.setSenha(uf);
        
        UsuarioDAO dao = new UsuarioDAO();
        dao.cadastrar(usuario);
        
        JTFcodigo.setText("");
        JTFnome.setText("");
        JTFemail.setText("");
        JTFsenha.setText("");
        JBpesquisar.setEnabled(true);
        JTFpesquisa.setEnabled(true);
        JTFnome.setEnabled(false);
        JTFemail.setEnabled(false);
        JTFsenha.setEnabled(false);
        JBnovo.setEnabled(true);
        JBsalvar.setEnabled(false);
        JBalterar.setEnabled(false);
        JBexcluir.setEnabled(false);
        JBcancelar.setEnabled(false);
    }//GEN-LAST:event_JBsalvarActionPerformed

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        JTFcodigo.setText("");
        JTFnome.setText("");
        JTFemail.setText("");
        JTFsenha.setText("");
        JBpesquisar.setEnabled(true);
        JTFpesquisa.setEnabled(true);
        JTFnome.setEnabled(false);
        JTFemail.setEnabled(false);
        JTFsenha.setEnabled(false);
        JBnovo.setEnabled(true);
        JBsalvar.setEnabled(false);
        JBalterar.setEnabled(false);
        JBexcluir.setEnabled(false);
        JBcancelar.setEnabled(false); 
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void JBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpesquisarActionPerformed
        String pesquisa = JTFpesquisa.getText();
        Usuario uso;
        UsuarioDAO daoUso = new UsuarioDAO();
        uso = daoUso.pesquisar(pesquisa);
        if(uso.getCodigo() == 0){
            JOptionPane.showMessageDialog(null, "Usuario não encontrada", "Cadastro Cidade", 0);
        }else{
            JTFcodigo.setText(Integer.toString(uso.getCodigo()));
            JTFnome.setText(uso.getNome());
            JTFemail.setText(uso.getEmail());
            JTFsenha.setText(uso.getSenha());
            JBnovo.setEnabled(false);
            JBalterar.setEnabled(true);
            JBexcluir.setEnabled(true);
            JTFnome.setEnabled(true);
            JTFemail.setEnabled(true);
            JTFsenha.setEnabled(true);
        }
    }//GEN-LAST:event_JBpesquisarActionPerformed

    private void JBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBalterarActionPerformed
        UsuarioDAO daoUso = new UsuarioDAO();
        String nome = JTFnome.getText();
        String email = JTFemail.getText();
        String senha = JTFsenha.getText();
        int codigo = Integer.parseInt(JTFcodigo.getText());
        
        Usuario usuario = new Usuario();
        usuario.setNome(nome);
        usuario.setEmail(email);
        usuario.setSenha(senha);
        usuario.setCodigo(codigo);
        
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente atualizar os dados do usuario","Mensagem do Sistema",0);
        if(opcao == 0){
            daoUso.alterar(usuario);
        
        JTFnome.setEnabled(false);
        JTFemail.setEnabled(false);
        JTFsenha.setEnabled(false);
        JBnovo.setEnabled(true);
        JBexcluir.setEnabled(false);
        JBcancelar.setEnabled(false);
        JBalterar.setEnabled(false);
        JBsalvar.setEnabled(false);
        JTFcodigo.setText("");
        JTFnome.setText("");
        JTFemail.setText("");
        JTFsenha.setText("");
        }
    }//GEN-LAST:event_JBalterarActionPerformed

    private void JBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexcluirActionPerformed
        int codigo = Integer.parseInt(JTFcodigo.getText());
        Usuario uso = new Usuario();
        uso.setCodigo(codigo);
        UsuarioDAO daoUso = new UsuarioDAO();
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o usuario","Mensagem do Sistema",0);
        if(opcao == 0){
            daoUso.deletar(uso);
        }
        JTFnome.setEnabled(false);
        JTFemail.setEnabled(false);
        JTFsenha.setEnabled(false);
        JBnovo.setEnabled(true);
        JBexcluir.setEnabled(false);
        JBcancelar.setEnabled(false);
        JBalterar.setEnabled(false);
        JBsalvar.setEnabled(false);
        JTFcodigo.setText("");
        JTFnome.setText("");
        JTFemail.setText("");
        JTFsenha.setText("");
    }//GEN-LAST:event_JBexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBalterar;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBexcluir;
    private javax.swing.JButton JBnovo;
    private javax.swing.JButton JBpesquisar;
    private javax.swing.JButton JBsalvar;
    private javax.swing.JTextField JTFcodigo;
    private javax.swing.JTextField JTFemail;
    private javax.swing.JTextField JTFnome;
    private javax.swing.JTextField JTFpesquisa;
    private javax.swing.JTextField JTFsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
