/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CidadeController;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.Cidade;

/**
 *
 * @author Pedro
 */
public class TelaCadCidadeInternalFrame extends javax.swing.JInternalFrame {

    CidadeController controller; //Objeto responsável pelo ControllerCidade
    Cidade cid; // Objeto Cidade
    int opcao;
    JDesktopPane areaTrabalho;
    TelaPrincipal telaPrincipal;
            
    public TelaCadCidadeInternalFrame() {
        initComponents();
        controller = new CidadeController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFpesquisar = new javax.swing.JTextField();
        JBpesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JTFcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTFcidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JCBestado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JTFpais = new javax.swing.JTextField();
        jBprimeiro = new javax.swing.JButton();
        jBanterior = new javax.swing.JButton();
        jBproximo = new javax.swing.JButton();
        jBultimo = new javax.swing.JButton();
        JBcancelar = new javax.swing.JButton();
        JBexcluir = new javax.swing.JButton();
        JBalterar = new javax.swing.JButton();
        JBsalvar = new javax.swing.JButton();
        JBnovo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastrar Cidade");

        jLabel1.setText("Pesquisar:");

        JTFpesquisar.setText("Digite o código ou nome da cidade");
        JTFpesquisar.setToolTipText("");
        JTFpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFpesquisarMouseClicked(evt);
            }
        });
        JTFpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFpesquisarKeyPressed(evt);
            }
        });

        JBpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        JBpesquisar.setText("Pesquisar");
        JBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpesquisarActionPerformed(evt);
            }
        });

        JTFcodigo.setEnabled(false);
        JTFcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Cidade:");

        JTFcidade.setEnabled(false);
        JTFcidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFcidadeFocusGained(evt);
            }
        });
        JTFcidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFcidadeMouseClicked(evt);
            }
        });
        JTFcidade.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JTFcidadePropertyChange(evt);
            }
        });

        jLabel4.setText("Estado:");

        JCBestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        JCBestado.setEnabled(false);

        jLabel5.setText("País:");

        JTFpais.setEnabled(false);
        JTFpais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFpaisMouseClicked(evt);
            }
        });

        jBprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/primeiro.png"))); // NOI18N
        jBprimeiro.setEnabled(false);
        jBprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprimeiroActionPerformed(evt);
            }
        });

        jBanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Anterior.png"))); // NOI18N
        jBanterior.setEnabled(false);
        jBanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanteriorActionPerformed(evt);
            }
        });

        jBproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Proximo.png"))); // NOI18N
        jBproximo.setEnabled(false);

        jBultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Ultimo.png"))); // NOI18N
        jBultimo.setEnabled(false);

        JBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        JBcancelar.setText("Cancelar");
        JBcancelar.setEnabled(false);
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });

        JBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        JBexcluir.setText("Excluir");
        JBexcluir.setEnabled(false);
        JBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexcluirActionPerformed(evt);
            }
        });

        JBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        JBalterar.setText("Alterar");
        JBalterar.setEnabled(false);
        JBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBalterarActionPerformed(evt);
            }
        });

        JBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/gravar.png"))); // NOI18N
        JBsalvar.setText("Salvar");
        JBsalvar.setToolTipText("");
        JBsalvar.setEnabled(false);
        JBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalvarActionPerformed(evt);
            }
        });

        JBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        JBnovo.setText("Novo");
        JBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JBnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFcidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCBestado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFpais))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBpesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCBestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(JTFpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBprimeiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBanterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBproximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBultimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBsalvar)
                    .addComponent(JBnovo)
                    .addComponent(JBalterar)
                    .addComponent(JBexcluir)
                    .addComponent(JBcancelar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFpesquisarMouseClicked
        JTFpesquisar.setText("");
    }//GEN-LAST:event_JTFpesquisarMouseClicked

    private void JTFpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFpesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pesquisar();
        }
    }//GEN-LAST:event_JTFpesquisarKeyPressed

    private void JBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_JBpesquisarActionPerformed

    private void JTFcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcodigoActionPerformed

    private void JTFcidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFcidadeMouseClicked
        if (JTFcidade.getText().equals("O campo nome não pode ficar vazio")) {
            JTFcidade.setText("");
            JTFcidade.setBackground(Color.white);
        }
    }//GEN-LAST:event_JTFcidadeMouseClicked

    private void JTFpaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFpaisMouseClicked
        if (JTFpais.getText().equals("O campo pais não pode ficar vazio")) {
            JTFpais.setText("");
            JTFpais.setBackground(Color.white);
        }
    }//GEN-LAST:event_JTFpaisMouseClicked

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        this.limparCampus();
        habilitarCampus(3);
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void JBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexcluirActionPerformed

        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a cidade", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);

        if (opcao == 0) {
            controller.deletar(this.criarObjeto());
            limparCampus();
            habilitarCampus(3);
        }
    }//GEN-LAST:event_JBexcluirActionPerformed

    private void JBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBalterarActionPerformed

        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente atualizar os dados da cidade", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        if (opcao == 0) {
            controller.alterar(this.criarObjeto());
            
            limparCampus();
            habilitarCampus(3);
        }
        if(this.getOpcao() == 1){
            TelaTabelaCidadeInternalFrame tabelaCidade = new TelaTabelaCidadeInternalFrame();
            tabelaCidade.setVisible(true);
            this.getAreaTrabalho().add(tabelaCidade);
            
            this.dispose();
        }
    }//GEN-LAST:event_JBalterarActionPerformed

    private void JBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalvarActionPerformed
        if (this.verificarCampus()) {
            controller.cadastrar(this.criarObjeto());
            limparCampus();
            habilitarCampus(3);
        }
        if(this.getOpcao() == 1){
            TelaTabelaCidadeInternalFrame tabelaCidade = new TelaTabelaCidadeInternalFrame();
            tabelaCidade.setVisible(true);
            this.getAreaTrabalho().add(tabelaCidade);
            
            this.dispose();
        }
    }//GEN-LAST:event_JBsalvarActionPerformed

    private void JBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnovoActionPerformed
        habilitarCampus(2);
    }//GEN-LAST:event_JBnovoActionPerformed

    private void jBprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprimeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBprimeiroActionPerformed

    private void jBanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBanteriorActionPerformed

    private void JTFcidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFcidadeFocusGained
        JTFpais.setBackground(Color.white);
    }//GEN-LAST:event_JTFcidadeFocusGained

    private void JTFcidadePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JTFcidadePropertyChange
        JTFpais.setBackground(Color.white);
    }//GEN-LAST:event_JTFcidadePropertyChange

    public void limparCampus() {
        JTFcodigo.setText("");
        JTFcidade.setText("");
        JTFpais.setText("");
        JTFpesquisar.setText("Digite o código ou nome da cidade");
        JCBestado.setSelectedIndex(0);
    }

    public void habilitarCampus(int btn) {
        switch (btn) {
            case 1://Botão Pesquisar
                JBnovo.setEnabled(false);
                JBalterar.setEnabled(true);
                JBexcluir.setEnabled(true);
                JBcancelar.setEnabled(true);
                JBsalvar.setEnabled(false);
                JTFcidade.setEnabled(true);
                JTFpais.setEnabled(true);
                JCBestado.setEnabled(true);
                jBanterior.setEnabled(true);
                jBprimeiro.setEnabled(true);
                jBproximo.setEnabled(true);
                jBultimo.setEnabled(true);
                break;
            case 2://Botão Novo
                JBsalvar.setEnabled(true);
                JBcancelar.setEnabled(true);
                JBpesquisar.setEnabled(false);
                JBalterar.setEnabled(false);
                JBnovo.setEnabled(false);
                JBexcluir.setEnabled(false);
                JTFpesquisar.setEnabled(false);
                JTFcidade.setEnabled(true);
                JTFpais.setEnabled(true);
                JCBestado.setEnabled(true);
                break;
            case 3://Botões Salvar, Alterar, Excluir e Cancelar
                JBpesquisar.setEnabled(true);
                JTFpesquisar.setEnabled(true);
                JTFcidade.setEnabled(false);
                JCBestado.setEnabled(false);
                JTFpais.setEnabled(false);
                JBnovo.setEnabled(true);
                JBsalvar.setEnabled(false);
                JBalterar.setEnabled(false);
                JBexcluir.setEnabled(false);
                JBcancelar.setEnabled(false);
                jBanterior.setEnabled(false);
                jBprimeiro.setEnabled(false);
                jBproximo.setEnabled(false);
                jBultimo.setEnabled(false);
                break;
            default:
                break;
        }
    }

    public Cidade criarObjeto() {
        cid = new Cidade();

        cid.setNome(JTFcidade.getText());
        cid.setUf(JCBestado.getSelectedItem().toString());
        cid.setPais(JTFpais.getText());
        if (JTFcodigo.getText().equals("")) {
            cid.setCodigo(0);
        } else {
            cid.setCodigo(Integer.parseInt(JTFcodigo.getText()));
        }

        return cid;
    }

    public void pesquisar() {
        cid = controller.pesquisar(JTFpesquisar.getText());

        if (cid.getCodigo() == 0) {
            this.limparCampus();
            this.habilitarCampus(3);
            JOptionPane.showMessageDialog(null, "Cidade não encontrada", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JTFcodigo.setText(Integer.toString(cid.getCodigo()));
            JTFcidade.setText(cid.getNome());
            JTFpais.setText(cid.getPais());
            JCBestado.setSelectedItem(cid.getUf());
            habilitarCampus(1);
        }
    }

    public void pesquisar(int codigo) {
        cid = controller.pesquisar(codigo);

        if (cid.getCodigo() == 0) {
            this.limparCampus();
            this.habilitarCampus(3);
            JOptionPane.showMessageDialog(null, "Cidade não encontrada", "Mensagem do Sistema", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JTFcodigo.setText(Integer.toString(cid.getCodigo()));
            JTFcidade.setText(cid.getNome());
            JTFpais.setText(cid.getPais());
            JCBestado.setSelectedItem(cid.getUf());
            habilitarCampus(1);
        }
    }

    public boolean verificarCampus() {

        boolean preenchido = true;

        if (JTFcidade.getText().isEmpty()) {
            JTFcidade.setText("O campo nome não pode ficar vazio");
            JTFcidade.setBackground(Color.YELLOW);
            preenchido = false;
        }
        if (JTFpais.getText().isEmpty()) {
            JTFpais.setText("O campo pais não pode ficar vazio");
            JTFpais.setBackground(Color.YELLOW);
            preenchido = false;
        }

        return preenchido;
    }
    
    public void setOpcao(int opcao){
        this.opcao = opcao;
    }
    
    public int getOpcao(){
        return this.opcao;
    }
    
    public void setAreaTrabalho(JDesktopPane areaTrabalho){
        this.areaTrabalho = areaTrabalho;
    }
    
    public JDesktopPane getAreaTrabalho(){
        return this.areaTrabalho;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBalterar;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBexcluir;
    private javax.swing.JButton JBnovo;
    private javax.swing.JButton JBpesquisar;
    private javax.swing.JButton JBsalvar;
    private javax.swing.JComboBox<String> JCBestado;
    private javax.swing.JTextField JTFcidade;
    private javax.swing.JTextField JTFcodigo;
    private javax.swing.JTextField JTFpais;
    private javax.swing.JTextField JTFpesquisar;
    private javax.swing.JButton jBanterior;
    private javax.swing.JButton jBprimeiro;
    private javax.swing.JButton jBproximo;
    private javax.swing.JButton jBultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
