/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CidadeDaoImpl;
import DAO.DAOCliente;
import controller.CidadeController;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;
import model.Cidade;
import model.Cliente;

/**
 *
 * @author PC18
 */
public class TelaCadCliente extends javax.swing.JFrame {

    CidadeController controllerCid;
    Cidade cid;
    ArrayList<Cidade> cidades;
    
    public TelaCadCliente() {
        initComponents();
        controllerCid = new CidadeController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFpesquisar = new javax.swing.JTextField();
        JBpesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JBnovo = new javax.swing.JButton();
        JBsalvar = new javax.swing.JButton();
        JBalterar = new javax.swing.JButton();
        JBexcluir = new javax.swing.JButton();
        JBcancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JTFrua = new javax.swing.JTextField();
        JTFbairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JTFcep = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JTFnumero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        JCBestado = new javax.swing.JComboBox<>();
        jCBCidade = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTFreferencia = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTFcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFnome = new javax.swing.JTextField();
        JTFrg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTFcpf = new javax.swing.JFormattedTextField();
        JTFemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JCBsexo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        JTFdataNascimento = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        JTFtelefone = new javax.swing.JFormattedTextField();
        JTFcelular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTFreferencia1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("telaCadCliente");

        jLabel1.setText("Pesquisa:");

        JBpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        JBpesquisar.setText("Pesquisar");
        JBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpesquisarActionPerformed(evt);
            }
        });

        JBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        JBnovo.setText("Novo");
        JBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnovoActionPerformed(evt);
            }
        });

        JBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/gravar.png"))); // NOI18N
        JBsalvar.setText("Salvar");
        JBsalvar.setEnabled(false);
        JBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalvarActionPerformed(evt);
            }
        });

        JBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        JBalterar.setText("Alterar");
        JBalterar.setEnabled(false);
        JBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBalterarActionPerformed(evt);
            }
        });

        JBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        JBexcluir.setText("Excluir");
        JBexcluir.setEnabled(false);
        JBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexcluirActionPerformed(evt);
            }
        });

        JBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        JBcancelar.setText("Cancelar");
        JBcancelar.setEnabled(false);
        JBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcancelarActionPerformed(evt);
            }
        });

        jLabel11.setText("Rua:");

        JTFrua.setEnabled(false);

        JTFbairro.setEnabled(false);

        jLabel14.setText("Bairro:");

        try {
            JTFcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTFcep.setEnabled(false);

        jLabel15.setText("Cep:");

        jLabel16.setText("N°:");

        JTFnumero.setEnabled(false);

        jLabel17.setText("UF:");

        JCBestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "Go", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        JCBestado.setEnabled(false);
        JCBestado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCBestadoItemStateChanged(evt);
            }
        });

        jCBCidade.setEnabled(false);

        jLabel18.setText("Cidade:");

        jLabel19.setText("Referência:");

        JTFreferencia.setColumns(20);
        JTFreferencia.setRows(5);
        JTFreferencia.setEnabled(false);
        jScrollPane1.setViewportView(JTFreferencia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JTFrua, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JTFnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFcep, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCBestado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JTFrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(JTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(JTFnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(JTFcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(JCBestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", jPanel1);

        jLabel3.setText("Código:");

        JTFcodigo.setEnabled(false);

        jLabel4.setText("Nome:");

        JTFnome.setEnabled(false);

        JTFrg.setEnabled(false);
        JTFrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFrgActionPerformed(evt);
            }
        });

        jLabel5.setText("RG:");

        jLabel9.setText("Cpf:");

        try {
            JTFcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTFcpf.setEnabled(false);
        JTFcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcpfActionPerformed(evt);
            }
        });

        JTFemail.setEnabled(false);

        jLabel6.setText("Email:");

        jLabel7.setText("Sexo");

        JCBsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        JCBsexo.setEnabled(false);

        jLabel12.setText("Data Nascimento:");

        try {
            JTFdataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTFdataNascimento.setEnabled(false);

        jLabel8.setText("Telefone:");

        try {
            JTFtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTFtelefone.setEnabled(false);

        try {
            JTFcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTFcelular.setEnabled(false);

        jLabel13.setText("Celular:");

        jLabel20.setText("Observações:");

        JTFreferencia1.setColumns(20);
        JTFreferencia1.setRows(5);
        JTFreferencia1.setEnabled(false);
        jScrollPane3.setViewportView(JTFreferencia1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JTFtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTFemail)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(JTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTFcpf))
                                .addComponent(JTFnome)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(JCBsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTFdataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(JTFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JCBsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(JTFdataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JTFtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(JTFcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel2);

        jTabbedPane1.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBpesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBnovo)
                        .addGap(18, 18, 18)
                        .addComponent(JBsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(JBalterar)
                        .addGap(18, 18, 18)
                        .addComponent(JBexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(JBcancelar))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnovo)
                    .addComponent(JBsalvar)
                    .addComponent(JBalterar)
                    .addComponent(JBexcluir)
                    .addComponent(JBcancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFrgActionPerformed

    private void JBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpesquisarActionPerformed
        Cliente cli;
        DAOCliente daocli = new DAOCliente();
        cli = daocli.pesquisar(JTFpesquisar.getText());
        if(cli.getCodigo() == 0){
            JOptionPane.showMessageDialog(null, "Cliente não encontrado", "Cadastro Cliente", 0);
        }else{
            JTFcodigo.setText(Integer.toString(cli.getCodigo()));
            JTFnome.setText(cli.getNome());
            JTFrg.setText(cli.getRg());
            JTFcpf.setText(cli.getCpf());
            JTFemail.setText(cli.getEmail());
            JCBsexo.setSelectedItem(cli.getSexo());
            JTFdataNascimento.setText(cli.getDataNasc());
            JTFtelefone.setText(cli.getTelefone());
            JTFcelular.setText(cli.getCelular());
            JTFrua.setText(cli.getRua());
            JTFbairro.setText(cli.getBairro());
            JTFnumero.setText(Integer.toString(cli.getNum()));
            JTFcep.setText(cli.getCep());
            
            CidadeDaoImpl daoCid = new CidadeDaoImpl();
            Cidade cid = daoCid.pesquisar(Integer.toString(cli.getCodigoCidade()));
                        
            JCBestado.setSelectedItem(cid.getUf());
          //  JTFcidade.setSelectedItem(cid.getNome());
            JTFreferencia.setText(cli.getReferencia());
            JBnovo.setEnabled(false);
            JBalterar.setEnabled(true);
            JBexcluir.setEnabled(true);
          //  JTFcidade.setEnabled(true);
            habilita();
            JBnovo.setEnabled(false);
            JBsalvar.setEnabled(false);
        }
    }//GEN-LAST:event_JBpesquisarActionPerformed

    public void habilita(){
        JTFpesquisar.setEnabled(false);
        JTFnome.setEnabled(true);
        JTFrg.setEnabled(true);
        JTFcpf.setEnabled(true);
        JTFemail.setEnabled(true);
        JCBsexo.setEnabled(true);
        JTFdataNascimento.setEnabled(true);
        JTFtelefone.setEnabled(true);
        JTFcelular.setEnabled(true);
        JTFrua.setEnabled(true);
        JTFbairro.setEnabled(true);
        JTFnumero.setEnabled(true);
        JTFcep.setEnabled(true);
        JCBestado.setEnabled(true);
     //   JTFcidade.setEnabled(true);
        JTFreferencia.setEnabled(true);
        JBpesquisar.setEnabled(false);
        JBnovo.setEnabled(false);
        JBsalvar.setEnabled(true);
        JBcancelar.setEnabled(true);    
    }
    
    private void JBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalvarActionPerformed
        String nome = JTFnome.getText();
        String rg = JTFrg.getText();
        String cpf = JTFcpf.getText();
        String email = JTFemail.getText();
        String sexo = (String) JCBsexo.getSelectedItem();
        String dataNasc = JTFdataNascimento.getText();
        String telefo = JTFtelefone.getText();
        String celular = JTFcelular .getText();
        String rua = JTFrua .getText();
        String bairro = JTFbairro .getText();
        int numero = Integer.parseInt(JTFnumero .getText());
        String cep = JTFcep .getText();
        String estado = (String) JCBestado.getSelectedItem();
      //  String cidade = (String) JTFcidade.getSelectedItem();
        String referencia = JTFreferencia .getText();
        
        Cliente cliente = new Cliente();
        cliente.setNome(nome);
        cliente.setRg(rg);
        cliente.setCpf(cpf);
        cliente.setEmail(email);
        cliente.setSexo(sexo);
        cliente.setDataNasc(dataNasc);
        cliente.setTelefone(telefo);
        cliente.setCelular(celular);
        cliente.setRua(rua);
        cliente.setBairro(bairro);
        cliente.setNum(numero);
        cliente.setCep(cep);
        cliente.setUf(estado);
       // cliente.setCidade(cidade);
        cliente.setReferencia(referencia);
        
        DAOCliente daoClie = new DAOCliente();
        daoClie.inserir(cliente);
        resetar();
        
    }//GEN-LAST:event_JBsalvarActionPerformed

    public void resetar(){
        JTFnome.setEnabled(false);
        JTFrg.setEnabled(false);
        JTFcpf.setEnabled(false);
        JTFemail.setEnabled(false);
        JCBsexo.setEnabled(false);
        JTFdataNascimento.setEnabled(false);
        JTFtelefone.setEnabled(false);
        JTFcelular.setEnabled(false);
        JTFrua.setEnabled(false);
        JTFbairro.setEnabled(false);
        JTFnumero.setEnabled(false);
        JTFcep.setEnabled(false);
        JCBestado.setEnabled(false);
      //  JTFcidade.setEnabled(false);
        JTFreferencia.setEnabled(false);
        JTFpesquisar.setEnabled(true);
        JBnovo.setEnabled(true);
        JBsalvar.setEnabled(false);
        JBcancelar.setEnabled(false);
        JBalterar.setEnabled(false);
        JBexcluir.setEnabled(false);
        JBpesquisar.setEnabled(true);
        JTFpesquisar.setText("");
        JTFcodigo.setText("");
        JTFnome.setText("");
        JTFrg.setText("");
        JTFcpf.setText("");
        JTFemail.setText("");
        JCBsexo.setSelectedItem(0);
        JTFdataNascimento.setText("");
        JTFtelefone.setText("");
        JTFcelular.setText("");
        JTFrua.setText("");
        JTFbairro.setText("");
        JTFnumero.setText("");
        JTFcep.setText("");
        JCBestado.setSelectedItem(0);
       // JTFcidade.setSelectedItem(0);
        JTFreferencia.setText("");
    }
    private void JBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnovoActionPerformed
        habilita();
    }//GEN-LAST:event_JBnovoActionPerformed

    private void JBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBalterarActionPerformed
        int codigo = Integer.parseInt(JTFcodigo.getText());
        String nome = JTFnome.getText();
        String rg = JTFrg.getText();
        String cpf = JTFcpf.getText();
        String email = JTFemail.getText();
        String sexo = (String) JCBsexo.getSelectedItem();
        String dataNasc = JTFdataNascimento.getText();
        String telefo = JTFtelefone.getText();
        String celular = JTFcelular .getText();
        String rua = JTFrua .getText();
        String bairro = JTFbairro .getText();
        int numero = Integer.parseInt(JTFnumero .getText());
        String cep = JTFcep .getText();
        String estado = (String) JCBestado.getSelectedItem();
       // String cidade = (String) JTFcidade.getSelectedItem();
        String referencia = JTFreferencia .getText();
        
        Cliente cliente = new Cliente();
        cliente.setNome(nome);
        cliente.setRg(rg);
        cliente.setCpf(cpf);
        cliente.setEmail(email);
        cliente.setSexo(sexo);
        cliente.setDataNasc(dataNasc);
        cliente.setTelefone(telefo);
        cliente.setCelular(celular);
        cliente.setRua(rua);
        cliente.setBairro(bairro);
        cliente.setNum(numero);
        cliente.setCep(cep);
        cliente.setUf(estado);
       // cliente.setCidade(cidade);
        cliente.setReferencia(referencia);
        
        DAOCliente daoCli = new DAOCliente();
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente atualizar os dados deste Cliente?","Mensagem do Sistema",0);
        if(opcao == 0){
            daoCli.atualizar(cliente);
        }
    }//GEN-LAST:event_JBalterarActionPerformed

    private void JCBestadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCBestadoItemStateChanged
        
        cidades = controllerCid.selecionarCidadesUF(
                (String)JCBestado.getSelectedItem());
        
        JCBestado.removeAllItems();
       
        for (Cidade cid : cidades) {
            jCBCidade.addItem(cid.getNome());
        }
        
    }//GEN-LAST:event_JCBestadoItemStateChanged

    private void JTFcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcpfActionPerformed

    private void JBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcancelarActionPerformed
        resetar();
    }//GEN-LAST:event_JBcancelarActionPerformed

    private void JBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexcluirActionPerformed
        int codigo = Integer.parseInt(JTFcodigo.getText());
        Cliente c = new Cliente();
        c.setCodigo(codigo);
        DAOCliente daoCli = new DAOCliente();
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este Cliente","Mensagem do Sistema",0);
        if(opcao == 0){
            daoCli.deletar(c);
        }
        resetar();
    }//GEN-LAST:event_JBexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBalterar;
    private javax.swing.JButton JBcancelar;
    private javax.swing.JButton JBexcluir;
    private javax.swing.JButton JBnovo;
    private javax.swing.JButton JBpesquisar;
    private javax.swing.JButton JBsalvar;
    private javax.swing.JComboBox<String> JCBestado;
    private javax.swing.JComboBox<String> JCBsexo;
    private javax.swing.JTextField JTFbairro;
    private javax.swing.JFormattedTextField JTFcelular;
    private javax.swing.JFormattedTextField JTFcep;
    private javax.swing.JTextField JTFcodigo;
    private javax.swing.JFormattedTextField JTFcpf;
    private javax.swing.JFormattedTextField JTFdataNascimento;
    private javax.swing.JTextField JTFemail;
    private javax.swing.JTextField JTFnome;
    private javax.swing.JTextField JTFnumero;
    private javax.swing.JTextField JTFpesquisar;
    private javax.swing.JTextArea JTFreferencia;
    private javax.swing.JTextArea JTFreferencia1;
    private javax.swing.JTextField JTFrg;
    private javax.swing.JTextField JTFrua;
    private javax.swing.JFormattedTextField JTFtelefone;
    private javax.swing.JComboBox<String> jCBCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
